### ISSUE TITLE
MPC 

### ISSUE THREAD

**Issue by Mahrokh98** [jmurraylouw/practical_quad#1]
HEY . 
could u please tell , where is the mpc part ?

**Comment by jmurraylouw** [comment]
In this repo: https://github.com/jmurraylouw/Quad_Sim_Murray

I use the MPC block from MATLAB Simulink.

Main simulation is in this file: https://github.com/jmurraylouw/Quad_Sim_Murray/blob/main/quad_simulation_with_payload.slx
